/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocomo.pkg2;

/**
 *
 * @author AREEB
 */
import java.lang.Math;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton76 = new javax.swing.JRadioButton();
        jRadioButton77 = new javax.swing.JRadioButton();
        jRadioButton78 = new javax.swing.JRadioButton();
        jRadioButton80 = new javax.swing.JRadioButton();
        jRadioButton81 = new javax.swing.JRadioButton();
        jRadioButton82 = new javax.swing.JRadioButton();
        jRadioButton83 = new javax.swing.JRadioButton();
        jRadioButton84 = new javax.swing.JRadioButton();
        jRadioButton86 = new javax.swing.JRadioButton();
        jRadioButton87 = new javax.swing.JRadioButton();
        jRadioButton88 = new javax.swing.JRadioButton();
        jRadioButton89 = new javax.swing.JRadioButton();
        jRadioButton90 = new javax.swing.JRadioButton();
        jRadioButton94 = new javax.swing.JRadioButton();
        jRadioButton95 = new javax.swing.JRadioButton();
        jRadioButton96 = new javax.swing.JRadioButton();
        jRadioButton92 = new javax.swing.JRadioButton();
        jRadioButton93 = new javax.swing.JRadioButton();
        jRadioButton100 = new javax.swing.JRadioButton();
        jRadioButton101 = new javax.swing.JRadioButton();
        jRadioButton102 = new javax.swing.JRadioButton();
        jRadioButton103 = new javax.swing.JRadioButton();
        jRadioButton106 = new javax.swing.JRadioButton();
        jRadioButton107 = new javax.swing.JRadioButton();
        jRadioButton108 = new javax.swing.JRadioButton();
        jRadioButton109 = new javax.swing.JRadioButton();
        jRadioButton111 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jRadioButton113 = new javax.swing.JRadioButton();
        jRadioButton114 = new javax.swing.JRadioButton();
        jRadioButton115 = new javax.swing.JRadioButton();
        jRadioButton116 = new javax.swing.JRadioButton();
        jRadioButton117 = new javax.swing.JRadioButton();
        jRadioButton118 = new javax.swing.JRadioButton();
        jRadioButton119 = new javax.swing.JRadioButton();
        jRadioButton120 = new javax.swing.JRadioButton();
        jRadioButton122 = new javax.swing.JRadioButton();
        jRadioButton123 = new javax.swing.JRadioButton();
        jRadioButton124 = new javax.swing.JRadioButton();
        jRadioButton125 = new javax.swing.JRadioButton();
        jRadioButton126 = new javax.swing.JRadioButton();
        jRadioButton127 = new javax.swing.JRadioButton();
        jRadioButton128 = new javax.swing.JRadioButton();
        jRadioButton129 = new javax.swing.JRadioButton();
        jRadioButton130 = new javax.swing.JRadioButton();
        jRadioButton131 = new javax.swing.JRadioButton();
        jRadioButton132 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("LANGUAGE FACTOR");

        jTextField1.setText("Enter SLOC");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("SLOC");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADA", "Assembly", "Basic", "C", "C++", "JAVA", "HTML 3.0", "Pascal", "PERL", "Spreadsheet", "Oracle" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate F.P.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("F.P.");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setText("SCALE DRIVERS ");

        jLabel6.setText("Precedentedness");

        jLabel7.setText("Architecture / Risk Resolution");

        jLabel8.setText("Process Maturity");

        jLabel9.setText("Development Flexibility");

        jLabel10.setText("Team Cohesion");

        jRadioButton1.setText("VERY LOW");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("LOW");

        jRadioButton3.setText("NOMINAL");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("HIGH");

        jRadioButton5.setText("VERY HIGH");

        jRadioButton6.setText("EXTRA HIGH");

        jRadioButton7.setText("VERY LOW");

        jRadioButton8.setText("LOW");

        jRadioButton9.setText("NORMAL");

        jRadioButton10.setText("HIGH");

        jRadioButton11.setText("VERY HIGH");

        jRadioButton12.setText("EXTRA HIGH");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton13.setText("VERY LOW");

        jRadioButton14.setText("LOW");

        jRadioButton15.setText("NORMAL");

        jRadioButton16.setText("HIGH");

        jRadioButton17.setText("VERY HIGH");

        jRadioButton18.setText("EXTRA HIGH");

        jRadioButton19.setText("VERY LOW");

        jRadioButton20.setText("LOW");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setText("NOMINAL");

        jRadioButton22.setText("HIGH");

        jRadioButton23.setText("VERY HIGH");

        jRadioButton24.setText("EXTRA HIGH");

        jRadioButton25.setText("VERY LOW");

        jRadioButton26.setText("LOW");

        jRadioButton27.setText("NOMINAL");

        jRadioButton28.setText("HIGH");

        jRadioButton29.setText("VERY HIGH");

        jRadioButton30.setText("EXTRA HIGH");

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel11.setText("COST DRIVERS");

        jLabel12.setText("Required Software Reliability");

        jLabel13.setText("Data Base Size");

        jLabel14.setText("Product Complexity");

        jLabel15.setText("Developed for Reusability");

        jLabel16.setText("Documentation Match to Lifecycle Needs");

        jLabel17.setText("Analyst Capability");

        jLabel18.setText("Programmer Capability");

        jLabel19.setText("Personnel Continuity");

        jLabel20.setText("Application Experience");

        jLabel21.setText("Platform Experience");

        jLabel22.setText("Language and Toolset Experience");

        jLabel23.setText("Time Constraint");

        jLabel24.setText("Storage Constraint");

        jLabel25.setText("Platform Volatility");

        jLabel26.setText("Use of Software Tools");

        jLabel27.setText("Multisite Development");

        jLabel28.setText("Required Development Schedule");

        jRadioButton31.setText("VERY LOW");

        jRadioButton32.setText("LOW");

        jRadioButton33.setText("NOMINAL");

        jRadioButton34.setText("HIGH");

        jRadioButton35.setText("VERY HIGH");

        jRadioButton38.setText("LOW");

        jRadioButton39.setText("NOMINAL");

        jRadioButton40.setText("HIGH");

        jRadioButton41.setText("VERY HIGH");

        jRadioButton43.setText("VERY LOW");

        jRadioButton44.setText("LOW");

        jRadioButton45.setText("NOMINAL");

        jRadioButton47.setText("LOW");

        jRadioButton49.setText("HIGH");

        jRadioButton50.setText("VERY HIGH");

        jRadioButton51.setText("EXTRA HIGH");

        jRadioButton52.setText("NOMINAL");

        jRadioButton53.setText("HIGH");

        jRadioButton54.setText("VERY HIGH");

        jRadioButton55.setText("EXTRA HIGH");
        jRadioButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton55ActionPerformed(evt);
            }
        });

        jRadioButton56.setText("VERY LOW");
        jRadioButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton56ActionPerformed(evt);
            }
        });

        jRadioButton57.setText("LOW");

        jRadioButton58.setText("NOMINAL");

        jRadioButton59.setText("HIGH");

        jRadioButton60.setText("VERY HIGH");

        jRadioButton62.setText("VERY LOW");
        jRadioButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton62ActionPerformed(evt);
            }
        });

        jRadioButton63.setText("LOW");

        jRadioButton64.setText("NOMINAL");

        jRadioButton65.setText("HIGH");

        jRadioButton66.setText("VERY HIGH");

        jRadioButton68.setText("VERY LOW");
        jRadioButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton68ActionPerformed(evt);
            }
        });

        jRadioButton69.setText("LOW");

        jRadioButton70.setText("NOMINAL");

        jRadioButton71.setText("HIGH");

        jRadioButton72.setText("VERY HIGH");
        jRadioButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton72ActionPerformed(evt);
            }
        });

        jRadioButton74.setText("VERY LOW");
        jRadioButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton74ActionPerformed(evt);
            }
        });

        jRadioButton75.setText("LOW");

        jRadioButton76.setText("NOMINAL");

        jRadioButton77.setText("HIGH");

        jRadioButton78.setText("VERY HIGH");
        jRadioButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton78ActionPerformed(evt);
            }
        });

        jRadioButton80.setText("VERY LOW");
        jRadioButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton80ActionPerformed(evt);
            }
        });

        jRadioButton81.setText("LOW");

        jRadioButton82.setText("NOMINAL");

        jRadioButton83.setText("HIGH");

        jRadioButton84.setText("VERY HIGH");
        jRadioButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton84ActionPerformed(evt);
            }
        });

        jRadioButton86.setText("VERY LOW");
        jRadioButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton86ActionPerformed(evt);
            }
        });

        jRadioButton87.setText("LOW");

        jRadioButton88.setText("NOMINAL");

        jRadioButton89.setText("HIGH");

        jRadioButton90.setText("VERY HIGH");
        jRadioButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton90ActionPerformed(evt);
            }
        });

        jRadioButton94.setText("VERY LOW");
        jRadioButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton94ActionPerformed(evt);
            }
        });

        jRadioButton95.setText("LOW");

        jRadioButton96.setText("NOMINAL");

        jRadioButton92.setText("HIGH");

        jRadioButton93.setText("VERY HIGH");
        jRadioButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton93ActionPerformed(evt);
            }
        });

        jRadioButton100.setText("NOMINAL");

        jRadioButton101.setText("HIGH");

        jRadioButton102.setText("VERY HIGH");
        jRadioButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton102ActionPerformed(evt);
            }
        });

        jRadioButton103.setText("EXTRA HIGH");
        jRadioButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton103ActionPerformed(evt);
            }
        });

        jRadioButton106.setText("NOMINAL");

        jRadioButton107.setText("HIGH");

        jRadioButton108.setText("VERY HIGH");
        jRadioButton108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton108ActionPerformed(evt);
            }
        });

        jRadioButton109.setText("EXTRA HIGH");
        jRadioButton109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton109ActionPerformed(evt);
            }
        });

        jRadioButton111.setText("LOW");

        jRadioButton112.setText("NOMINAL");

        jRadioButton113.setText("HIGH");

        jRadioButton114.setText("VERY HIGH");
        jRadioButton114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton114ActionPerformed(evt);
            }
        });

        jRadioButton115.setText("EXTRA HIGH");
        jRadioButton115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton115ActionPerformed(evt);
            }
        });

        jRadioButton116.setText("VERY LOW");
        jRadioButton116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton116ActionPerformed(evt);
            }
        });

        jRadioButton117.setText("LOW");

        jRadioButton118.setText("NOMINAL");

        jRadioButton119.setText("HIGH");

        jRadioButton120.setText("VERY HIGH");
        jRadioButton120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton120ActionPerformed(evt);
            }
        });

        jRadioButton122.setText("VERY LOW");
        jRadioButton122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton122ActionPerformed(evt);
            }
        });

        jRadioButton123.setText("LOW");

        jRadioButton124.setText("NOMINAL");

        jRadioButton125.setText("HIGH");

        jRadioButton126.setText("VERY HIGH");
        jRadioButton126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton126ActionPerformed(evt);
            }
        });

        jRadioButton127.setText("EXTRA HIGH");
        jRadioButton127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton127ActionPerformed(evt);
            }
        });

        jRadioButton128.setText("VERY LOW");
        jRadioButton128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton128ActionPerformed(evt);
            }
        });

        jRadioButton129.setText("LOW");

        jRadioButton130.setText("NOMINAL");

        jRadioButton131.setText("HIGH");

        jRadioButton132.setText("VERY HIGH");
        jRadioButton132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton132ActionPerformed(evt);
            }
        });

        jLabel29.setText("LABOUR RATE");

        jTextField2.setText("ENTER THE LABOUR RATE");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel30.setText("in (currency/person-month)");

        jLabel31.setText("P/M IS");

        jLabel33.setText("TIME OF DEVELOPMENT ");

        jLabel36.setText("COST OF DEVELOPMENT IS ");

        jButton2.setText("CALCULATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(82, 82, 82)
                        .addComponent(jRadioButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jRadioButton38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton39))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton33))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton43)
                                            .addComponent(jRadioButton56)
                                            .addComponent(jRadioButton62)
                                            .addComponent(jRadioButton68)
                                            .addComponent(jRadioButton74)
                                            .addComponent(jRadioButton80)
                                            .addComponent(jRadioButton86)
                                            .addComponent(jRadioButton94)
                                            .addComponent(jRadioButton116)
                                            .addComponent(jRadioButton122)
                                            .addComponent(jRadioButton128))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton47)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton52))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton45))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton57)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton58))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton63)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton64))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton69)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton70))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton75)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton76))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton81)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton82))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton87)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton88))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton95)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton96))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton111)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton112))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton117)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton118))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton123)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton124))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton129)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton130))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton100)
                                                    .addComponent(jRadioButton106)))))))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton60))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton77)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton78))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton83)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton84))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton89)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton92)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton93))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton101)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton102)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton107)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton108)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton109))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton113)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton114)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton115))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton119)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton120))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton125)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton126)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton127))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton131)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton132))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(79, 79, 79)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton40)
                    .addComponent(jRadioButton41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton44)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton58)
                    .addComponent(jRadioButton59)
                    .addComponent(jRadioButton60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton62)
                    .addComponent(jRadioButton63)
                    .addComponent(jRadioButton64)
                    .addComponent(jRadioButton65)
                    .addComponent(jRadioButton66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButton68)
                    .addComponent(jRadioButton69)
                    .addComponent(jRadioButton70)
                    .addComponent(jRadioButton71)
                    .addComponent(jRadioButton72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton74)
                    .addComponent(jRadioButton75)
                    .addComponent(jRadioButton76)
                    .addComponent(jRadioButton77)
                    .addComponent(jRadioButton78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jRadioButton80)
                    .addComponent(jRadioButton81)
                    .addComponent(jRadioButton82)
                    .addComponent(jRadioButton83)
                    .addComponent(jRadioButton84))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jRadioButton86)
                    .addComponent(jRadioButton87)
                    .addComponent(jRadioButton88)
                    .addComponent(jRadioButton89)
                    .addComponent(jRadioButton90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jRadioButton94)
                    .addComponent(jRadioButton95)
                    .addComponent(jRadioButton96)
                    .addComponent(jRadioButton92)
                    .addComponent(jRadioButton93))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jRadioButton100)
                    .addComponent(jRadioButton101)
                    .addComponent(jRadioButton102)
                    .addComponent(jRadioButton103))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jRadioButton106)
                    .addComponent(jRadioButton107)
                    .addComponent(jRadioButton108)
                    .addComponent(jRadioButton109))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jRadioButton111)
                    .addComponent(jRadioButton112)
                    .addComponent(jRadioButton113)
                    .addComponent(jRadioButton114)
                    .addComponent(jRadioButton115))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jRadioButton116)
                    .addComponent(jRadioButton117)
                    .addComponent(jRadioButton118)
                    .addComponent(jRadioButton119)
                    .addComponent(jRadioButton120))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jRadioButton122)
                    .addComponent(jRadioButton123)
                    .addComponent(jRadioButton124)
                    .addComponent(jRadioButton125)
                    .addComponent(jRadioButton126)
                    .addComponent(jRadioButton127))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jRadioButton128)
                    .addComponent(jRadioButton129)
                    .addComponent(jRadioButton130)
                    .addComponent(jRadioButton131)
                    .addComponent(jRadioButton132))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton109ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton109ActionPerformed

    private void jRadioButton108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton108ActionPerformed

    private void jRadioButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton103ActionPerformed

    private void jRadioButton102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton102ActionPerformed

    private void jRadioButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton93ActionPerformed

    private void jRadioButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton94ActionPerformed

    private void jRadioButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton90ActionPerformed

    private void jRadioButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton86ActionPerformed

    private void jRadioButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton84ActionPerformed

    private void jRadioButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton80ActionPerformed

    private void jRadioButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton78ActionPerformed

    private void jRadioButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton74ActionPerformed

    private void jRadioButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton72ActionPerformed

    private void jRadioButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton68ActionPerformed

    private void jRadioButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton62ActionPerformed

    private void jRadioButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton56ActionPerformed

    private void jRadioButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton55ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int sloc = Integer.parseInt(this.jTextField1.getText());
        String selectedValue = jComboBox1.getSelectedItem().toString();
        int languagevalue=0;
        if(selectedValue.equals("ADA"))
        {
            languagevalue = 71;
        }
        else if(selectedValue.equals("Assembly"))
        {
            languagevalue = 320;
        }
        else if(selectedValue.equals("Basic"))
        {
            languagevalue = 64;
        }
        else if(selectedValue.equals("C"))
        {
            languagevalue = 128;
        }
        else if(selectedValue.equals("C++"))
        {
            languagevalue = 53;
        }
        else if(selectedValue.equals("JAVA"))
        {
            languagevalue = 53;
        }
        else if(selectedValue.equals("HTML 3.0"))
        {
            languagevalue = 15;
        }
        else if(selectedValue.equals("Pascal"))
        {
            languagevalue = 91;
        }
        else if(selectedValue.equals("PERL"))
        {
            languagevalue = 27;
        }
        else if(selectedValue.equals("Spreadsheet"))
        {
            languagevalue = 6;
        }
        else if(selectedValue.equals("Oracle"))
        {
            languagevalue = 40;
        }
        double fp = sloc/languagevalue;
        this.jLabel4.setText("is "+ fp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //String selectedValue = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton114ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton114ActionPerformed

    private void jRadioButton115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton115ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton115ActionPerformed

    private void jRadioButton116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton116ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton116ActionPerformed

    private void jRadioButton120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton120ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton120ActionPerformed

    private void jRadioButton122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton122ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton122ActionPerformed

    private void jRadioButton126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton126ActionPerformed

    private void jRadioButton127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton127ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton127ActionPerformed

    private void jRadioButton128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton128ActionPerformed

    private void jRadioButton132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton132ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton132ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double labourrate = Integer.parseInt(this.jTextField1.getText());
        double a = 2.94,b = .91, c = 3.67,d = .28;
        double scale1=0,scale2=0,scale3=0,scale4=0,scale5=0,cost1=0,cost2=0,cost3=0,cost4=0,cost5=0,cost6=0,cost7=0,cost8=0,cost9=0,cost10=0,cost11=0,cost12=0,cost13=0,cost14=0,cost15=0,cost16=0,cost17=0;
        if(evt.getActionCommand().equals("CALCULATE"))
        {
           if(jRadioButton1.isSelected())
           {
               scale1 = 4.05;
           }
           else if(jRadioButton2.isSelected())
           {
               scale1 = 3.24;
           }
           else if(jRadioButton3.isSelected())
           {
               scale1 = 2.53;
           }
           else if(jRadioButton4.isSelected())
           {
               scale1 = 1.62;
           }
           else if(jRadioButton5.isSelected())
           {
               scale1 = .81;
           }
           else if(jRadioButton6.isSelected())
           {
               scale1 = 0.0;
           }
           if(jRadioButton7.isSelected())
           {
               scale2 = 6.07;
           }
           else if(jRadioButton8.isSelected())
           {
               scale2 = 4.86;
           }
           else if(jRadioButton9.isSelected())
           {
               scale2 = 3.64;
           }
           else if(jRadioButton10.isSelected())
           {
               scale2 = 2.43;
           }
           else if(jRadioButton11.isSelected())
           {
               scale2 = 1.21;
           }
           else if(jRadioButton12.isSelected())
           {
               scale2 = 0.0;
           }
           if(jRadioButton13.isSelected())
           {
               scale3 = 4.22;
           }
           else if(jRadioButton14.isSelected())
           {
               scale3 = 3.38;
           }
           else if(jRadioButton15.isSelected())
           {
               scale3 = 2.53;
           }
           else if(jRadioButton16.isSelected())
           {
               scale3 = 1.69;
           }
           else if(jRadioButton17.isSelected())
           {
               scale3 = .84;
           }
           else if(jRadioButton18.isSelected())
           {
               scale3 = 0.0;
           }
           if(jRadioButton19.isSelected())
           {
               scale4 = 4.94;
           }
           else if(jRadioButton20.isSelected())
           {
               scale4 = 3.95;
           }
           else if(jRadioButton21.isSelected())
           {
               scale4 = 2.97;
           }
           else if(jRadioButton22.isSelected())
           {
               scale4 = 1.98;
           }
           else if(jRadioButton23.isSelected())
           {
               scale4 = .99;
           }
           else if(jRadioButton24.isSelected())
           {
               scale4 = 0.0;
           }
           if(jRadioButton25.isSelected())
           {
               scale5 = 4.54;
           }
           else if(jRadioButton26.isSelected())
           {
               scale5 = 3.64;
           }
           else if(jRadioButton27.isSelected())
           {
               scale5 = 2.73;
           }
           else if(jRadioButton28.isSelected())
           {
               scale5 = 1.82;
           }
           else if(jRadioButton29.isSelected())
           {
               scale5 = .91;
           }
           else if(jRadioButton30.isSelected())
           {
               scale5 = 0.0;
           }
           if(jRadioButton31.isSelected())
           {
               cost1 = .75;
           }
           else if(jRadioButton32.isSelected())
           {
               cost1 = .88;
           }
           else if(jRadioButton33.isSelected())
           {
               cost1 = 1.00;
           }
           else if(jRadioButton34.isSelected())
           {
               cost1 = 1.15;
           }
           else if(jRadioButton35.isSelected())
           {
               cost1 = 1.39;
           }
           if(jRadioButton38.isSelected())
           {
               cost2 = .93;
           }
           else if(jRadioButton39.isSelected())
           {
               cost2 = 1.00;
           }
           else if(jRadioButton40.isSelected())
           {
               cost2 = 1.09;
           }
           else if(jRadioButton41.isSelected())
           {
               cost2 = 1.19;
           }
           if(jRadioButton43.isSelected())
           {
               cost3 = .75;
           }
           else if(jRadioButton44.isSelected())
           {
               cost3 = 0.88;
           }
           else if(jRadioButton45.isSelected())
           {
               cost3 = 1.00;
           }
           else if(jRadioButton49.isSelected())
           {
               cost3 = 1.15;
           }
           else if(jRadioButton50.isSelected())
           {
               cost3 = 1.30;
           }
           else if(jRadioButton51.isSelected())
           {
               cost3 = 1.66;
           }
           if(jRadioButton47.isSelected())
           {
               cost4 = .91;
           }
           else if(jRadioButton52.isSelected())
           {
               cost4 = 1.00;
           }
           else if(jRadioButton53.isSelected())
           {
               cost4 = 1.14;
           }
           else if(jRadioButton54.isSelected())
           {
               cost4 = 1.29;
           }
           else if(jRadioButton55.isSelected())
           {
               cost4 = 1.49;
           }
           if(jRadioButton56.isSelected())
           {
               cost5 = .89;
           }
           else if(jRadioButton57.isSelected())
           {
               cost5 = .95;
           }
           else if(jRadioButton58.isSelected())
           {
               cost5 = 1.00;
           }
           else if(jRadioButton59.isSelected())
           {
               cost5 = 1.06;
           }
           else if(jRadioButton60.isSelected())
           {
               cost5 = 1.13;
           }
           if(jRadioButton62.isSelected())
           {
               cost6 = 1.50;
           }
           else if(jRadioButton63.isSelected())
           {
               cost6 = 1.22;
           }
           else if(jRadioButton64.isSelected())
           {
               cost6 = 1.00;
           }
           else if(jRadioButton65.isSelected())
           {
               cost6 = 0.83;
           }
           else if(jRadioButton66.isSelected())
           {
               cost6 = 0.67;
           }
           if(jRadioButton68.isSelected())
           {
               cost7 = 1.37;
           }
           else if(jRadioButton69.isSelected())
           {
               cost7 = 1.16;
           }
           else if(jRadioButton70.isSelected())
           {
               cost7 = 1.00;
           }
           else if(jRadioButton71.isSelected())
           {
               cost7 = 0.87;
           }
           else if(jRadioButton72.isSelected())
           {
               cost7 = 0.74;
           }
           if(jRadioButton74.isSelected())
           {
               cost8 = 1.24;
           }
           else if(jRadioButton75.isSelected())
           {
               cost8 = 1.10;
           }
           else if(jRadioButton76.isSelected())
           {
               cost8 = 1.00;
           }
           else if(jRadioButton77.isSelected())
           {
               cost8 = 0.92;
           }
           else if(jRadioButton78.isSelected())
           {
               cost8 = 0.84;
           }
           if(jRadioButton80.isSelected())
           {
               cost9 = 1.22;
           }
           else if(jRadioButton81.isSelected())
           {
               cost9 = 1.10;
           }
           else if(jRadioButton82.isSelected())
           {
               cost9 = 1.00;
           }
           else if(jRadioButton83.isSelected())
           {
               cost9 = 0.89;
           }
           else if(jRadioButton84.isSelected())
           {
               cost9 = 0.81;
           }
           if(jRadioButton86.isSelected())
           {
               cost10 = 1.25;
           }
           else if(jRadioButton87.isSelected())
           {
               cost10 = 1.12;
           }
           else if(jRadioButton88.isSelected())
           {
               cost10 = 1.00;
           }
           else if(jRadioButton89.isSelected())
           {
               cost10 = 0.88;
           }
           else if(jRadioButton90.isSelected())
           {
               cost10 = 0.81;
           }
           if(jRadioButton94.isSelected())
           {
               cost11 = 1.22;
           }
           else if(jRadioButton95.isSelected())
           {
               cost11 = 1.10;
           }
           else if(jRadioButton96.isSelected())
           {
               cost11 = 1.00;
           }
           else if(jRadioButton92.isSelected())
           {
               cost11 = 0.91;
           }
           else if(jRadioButton93.isSelected())
           {
               cost11 = 0.84;
           }
           if(jRadioButton100.isSelected())
           {
               cost12 = 1.00;
           }
           else if(jRadioButton101.isSelected())
           {
               cost12 = 1.11;
           }
           else if(jRadioButton102.isSelected())
           {
               cost12 = 1.31;
           }
           else if(jRadioButton103.isSelected())
           {
               cost12 = 1.67;
           }
           if(jRadioButton106.isSelected())
           {
               cost13 = 1.00;
           }
           else if(jRadioButton107.isSelected())
           {
               cost13 = 1.11;
           }
           else if(jRadioButton108.isSelected())
           {
               cost13 = 1.31;
           }
           else if(jRadioButton109.isSelected())
           {
               cost13 = 1.67;
           }
           if(jRadioButton111.isSelected())
           {
               cost14 =0.87;
           }
           else if(jRadioButton112.isSelected())
           {
               cost14 = 1.00;
           }
           else if(jRadioButton113.isSelected())
           {
               cost14 = 1.15;
           }
           else if(jRadioButton114.isSelected())
           {
               cost14 = 1.30;
           }
           if(jRadioButton116.isSelected())
           {
               cost15 =1.24;
           }
           else if(jRadioButton117.isSelected())
           {
               cost15 = 1.12;
           }
           else if(jRadioButton118.isSelected())
           {
               cost15 = 1.00;
           }
           else if(jRadioButton119.isSelected())
           {
               cost15 = .86;
           }
           else if(jRadioButton120.isSelected())
           {
               cost15 = .72;
           }
           if(jRadioButton122.isSelected())
           {
               cost16 =1.25;
           }
           else if(jRadioButton123.isSelected())
           {
               cost16 = 1.10;
           }
           else if(jRadioButton124.isSelected())
           {
               cost16 = 1.00;
           }
           else if(jRadioButton125.isSelected())
           {
               cost16 = .92;
           }
           else if(jRadioButton126.isSelected())
           {
               cost16 = .84;
           }
           else if(jRadioButton127.isSelected())
           {
               cost16 = .78;
           }
           if(jRadioButton122.isSelected())
           {
               cost16 =1.25;
           }
           else if(jRadioButton123.isSelected())
           {
               cost16 = 1.10;
           }
           else if(jRadioButton124.isSelected())
           {
               cost16 = 1.00;
           }
           else if(jRadioButton125.isSelected())
           {
               cost16 = .92;
           }
           else if(jRadioButton126.isSelected())
           {
               cost16 = .84;
           }
           else if(jRadioButton127.isSelected())
           {
               cost16 = .78;
           }
           if(jRadioButton128.isSelected())
           {
               cost17 =1.29;
           }
           else if(jRadioButton129.isSelected())
           {
               cost17 = 1.10;
           }
           else if(jRadioButton130.isSelected())
           {
               cost17 = 1.00;
           }
           else if(jRadioButton131.isSelected())
           {
               cost17 = 1.00;
           }
           else if(jRadioButton132.isSelected())
           {
               cost17 = 1.00;
           }
           double pm,sloc,tdev,e;
           e = b + .01*(scale1+scale2+scale3+scale4+scale5);
           sloc = Integer.parseInt(this.jTextField1.getText());
           pm = a*Math.pow(sloc, e)*(cost1*cost2*cost3*cost4*cost5*cost6*cost7*cost8*cost9*cost10*cost11*cost12*cost13*cost14*cost15*cost16*cost17);
           double f = d + 0.2*( e - b );
           tdev = c * Math.pow(pm,f);
           double dev = labourrate*pm;
           this.jLabel35.setText("is "+ pm + " Effort");
           this.jLabel34.setText("is "+ tdev+ " months ");
           this.jLabel37.setText("is "+ dev + " $ ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton100;
    private javax.swing.JRadioButton jRadioButton101;
    private javax.swing.JRadioButton jRadioButton102;
    private javax.swing.JRadioButton jRadioButton103;
    private javax.swing.JRadioButton jRadioButton106;
    private javax.swing.JRadioButton jRadioButton107;
    private javax.swing.JRadioButton jRadioButton108;
    private javax.swing.JRadioButton jRadioButton109;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton111;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton113;
    private javax.swing.JRadioButton jRadioButton114;
    private javax.swing.JRadioButton jRadioButton115;
    private javax.swing.JRadioButton jRadioButton116;
    private javax.swing.JRadioButton jRadioButton117;
    private javax.swing.JRadioButton jRadioButton118;
    private javax.swing.JRadioButton jRadioButton119;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton120;
    private javax.swing.JRadioButton jRadioButton122;
    private javax.swing.JRadioButton jRadioButton123;
    private javax.swing.JRadioButton jRadioButton124;
    private javax.swing.JRadioButton jRadioButton125;
    private javax.swing.JRadioButton jRadioButton126;
    private javax.swing.JRadioButton jRadioButton127;
    private javax.swing.JRadioButton jRadioButton128;
    private javax.swing.JRadioButton jRadioButton129;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton130;
    private javax.swing.JRadioButton jRadioButton131;
    private javax.swing.JRadioButton jRadioButton132;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton77;
    private javax.swing.JRadioButton jRadioButton78;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton80;
    private javax.swing.JRadioButton jRadioButton81;
    private javax.swing.JRadioButton jRadioButton82;
    private javax.swing.JRadioButton jRadioButton83;
    private javax.swing.JRadioButton jRadioButton84;
    private javax.swing.JRadioButton jRadioButton86;
    private javax.swing.JRadioButton jRadioButton87;
    private javax.swing.JRadioButton jRadioButton88;
    private javax.swing.JRadioButton jRadioButton89;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButton90;
    private javax.swing.JRadioButton jRadioButton92;
    private javax.swing.JRadioButton jRadioButton93;
    private javax.swing.JRadioButton jRadioButton94;
    private javax.swing.JRadioButton jRadioButton95;
    private javax.swing.JRadioButton jRadioButton96;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
